# [START gae_quickstart_yaml]
runtime: nodejs10

env_variables:
  DB_PASSWORD: ngojosh1NJ
  DB_USERNAME: myPortfolio
  SECRET_KEY: "jfajofiaijoehnrajbefajfandjkf;aljfiw90u0293"
  AUTH_USERNAME: "kristofajosh"
  AUTH_PASSWORD: "myportfolio!@#"
  EMAIL_ADDRESS: "mydisposemail18@gmail.com"
  EMAIL_PASSWORD: "disposemail!@#"
  EMAIL_TO: "christopherjoshua18@live.com"
  EMAIL_BCC: "christopherjoshua18@gmail.com, christopherjoshua25@hotmail.com"
# [END gae_quickstart_yaml]